project_id = "kthxektvgaidqjetjsur"

[functions.create-client-account]
verify_jwt = false

[functions.monitor-services]
verify_jwt = false

[functions.resend-credentials]
verify_jwt = false

[functions.ping]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-service-payment]
verify_jwt = false
