project_id = "kthxektvgaidqjetjsur"

[functions.create-client-account]
verify_jwt = false

[functions.monitor-services]
verify_jwt = false

[functions.resend-credentials]
verify_jwt = false

[functions.ping]
verify_jwt = false
